### PR TITLE
feat: javascript and typescript migrations

### PR DESCRIPTION
**Pull request by mmkal**
fixes https://github.com/mmkal/slonik-tools/issues/45 and https://github.com/mmkal/slonik-tools/issues/141

### CODE REVIEW

**Comment by karlhorky** [comment]
Just trying this... TypeScript support is not working:

```
Unhandled rejection /Users/k/p/next.js-with-slonik/migrations/2019-10-23T08-22.database-setup.ts:10
type MigrationOptions = {
     ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.scriptResolver (/Users/k/p/next.js-with-slonik/node_modules/@slonik/migrator/dist/index.js:25:32)
    at migrationResolver (/Users/k/p/next.js-with-slonik/node_modules/@slonik/migrator/dist/index.js:46:45)
    at Object.customResolver (/Users/k/p/next.js-with-slonik/node_modules/@slonik/migrator/dist/index.js:66:37)
    at Migration.migration (/Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:60:38)
    at /Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:121:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:9:103)
    at _next (/Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:11:194)
    at /Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:11:364
```

**Comment by karlhorky** [comment]
Would also like to use ES module imports, eg:

```ts
import type { DatabasePoolConnectionType, SqlTaggedTemplateType } from 'slonik';
import { createPool } from 'slonik';
```

These are also not working:

```
Unhandled rejection /Users/k/p/next.js-with-slonik/migrations/2019-10-23T08-22.database-setup.ts:3
import type { DatabasePoolConnectionType, SqlTaggedTemplateType } from 'slonik';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.scriptResolver (/Users/k/p/next.js-with-slonik/node_modules/@slonik/migrator/dist/index.js:25:32)
    at migrationResolver (/Users/k/p/next.js-with-slonik/node_modules/@slonik/migrator/dist/index.js:46:45)
    at Object.customResolver (/Users/k/p/next.js-with-slonik/node_modules/@slonik/migrator/dist/index.js:66:37)
    at Migration.migration (/Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:60:38)
    at /Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:121:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:9:103)
    at _next (/Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:11:194)
    at /Users/k/p/next.js-with-slonik/node_modules/umzug/lib/migration.js:11:364
```

My `tsconfig.json` is set up to allow ES Modules: https://github.com/karlhorky/next.js-with-slonik/blob/master/tsconfig.json

**Comment by karlhorky** [comment]
Anyway, going to use JavaScript for now.

**Comment by mmkal** [comment]
You probably need ts-node. See the "JavaScript and TypeScript migrations" section of the [readme](https://github.com/mmkal/slonik-tools/tree/master/packages/migrator#readme):

>Note: if writing migrations in typescript, you will likely want to use a tool like ts-node to enable loading typescript modules. You can either add `require('ts-node/register/transpile-only')` at the top of your migrate.js file, or run `node -r ts-node/register/transpile-only migrate ...` instead of `node migrate ....`

**Comment by karlhorky** [comment]
Ah ok, yeah that's a bit much, maybe at some point later...

**Pull request merged**
