### PR TITLE
chore: update `pgsql-ast-parser` dependency to support `SKIP LOCKED` and `NOWAIT`

### PR DESCRIPTION
**Pull request by arajski**
# Description
Implements issue https://github.com/mmkal/slonik-tools/issues/419 
New release of [pgsql-ast-parser 11.1.0](https://github.com/oguimbal/pgsql-ast-parser/releases/tag/11.1.0) supports clauses `SKIP LOCKED` and `NOWAIT` which are especially useful in distributed system architectures.
Without it, such quaries have to be ignored using `-- typegen-ignore`

# Changes
- Updated the `pgsql-ast-parser` dependency version in `typegen`
- Fixed build problems
- Written some simple tests

# Notes
I'm not fully across which parts of the codebase have to be updated for features like that, so let me know if anything's missing or need to be changed.

### CODE REVIEW

**Comment by mmkal** [comment]
This looks great to me! Let's see how CI likes it. It's been a while since a version bump because of too many breaking changes in slonik, but hopefully this can be released as is without changing slonik supported version.

**Comment by arajski** [comment]
Looks good so far 🤞 what would be the next step?

**Comment by mmkal** [comment]
Having some trouble auto publishing, should be able to do it manually this weekend.

**Comment by mmkal** [comment]
finally released: [npm](https://www.npmjs.com/package/@slonik/typegen/v/0.15.0) [github](https://github.com/mmkal/slonik-tools/releases/tag/%40slonik%2Ftypegen%400.15.0)

**Comment by mmkal** [comment]
Thanks @arajski and sorry about the delay!

**Pull request merged**
