### PR TITLE
feat: support property transformations

### PR DESCRIPTION
**Pull request by mmkal**
fixes https://github.com/mmkal/slonik-tools/issues/72

I'll let this bake for a little while though, I have some reservations about it:

* `transformProperty` and `typeMapper` are conceptually similar. It makes the API a little more confusing - maybe these two could be merged somehow.
* It requires manually duplicating the behaviour of `slonik-interceptor-field-name-transformation` - I'd be interested to figure out if there's a more automatic way that just uses existing interceptors.
* I'm still unconvinced of the value of a field-name-transforming interceptor. It confuses tools like this, and makes it hard to discern that the source of a property is a database column.
* The way I've tested this is in the demo package. I'd like to find a way to test it more directly, because the demo package is used as pseudo-documentation; I don't want to imply that this is the recommended way to use the package. But if this change goes in, I _do_ want to document it.

@moltar if this is still an issue for you, and you'd be interested in helping test it, I could publish a canary package to npm so you can try it out.

### CODE REVIEW

**Comment by charlex** [comment]
@mmkal I'd be interested in seeing this published to canary and would be willing to help test.

**Comment by mmkal** [comment]
@charlex ok, I've published a [canary release](https://www.npmjs.com/package/@slonik/typegen/v/0.3.2-transform-properties.4). You can install with `npm i @slonik/typegen@transform-properties`. Let me know how it works out for you.

**Comment by charlex** [comment]
@mmkal Trying out now, will let you know how it goes. Sorry for my delay!

**Comment by charlex** [comment]
It worked!

>It requires manually duplicating the behaviour of slonik-interceptor-field-name-transformation - I'd be interested to figure out if there's a more automatic way that just uses existing interceptors.

Because I didn't read this at first, it took me a moment to realize that I had to add `transformProperty`. I figured it out, and it started working!

--

I am starting to come around to sharing your opinion though that name transformations are not really ideal. It might be nice to implement when my project is a bit more mature, but for now I think I might give up on transformations to focus on more productive endeavors.

If you're OCD and you really want to enforce a certain style throughout the project, this might be useful.

**Pull request closed without merging**
