### PR TITLE
feat(logs): improve log output

### PR DESCRIPTION
**Pull request by janpaepke**
## Feature Description

Even though these changes might look extensive, they are merely cosmetic and non-breaking (as confirmed by tests).  
There are no API or behavioural changes.  
Changes in tests are just to reflect new output.

The changes include:
- sync logging output between 'watch' and 'all files' mode.
- remove need for memoization in watch
- use paths relative to process, instead of absolute paths. This will make the output a lot more readable and keep paths 'clickable', when run inside for example vscode.
- run file-by-file instead of for all files.  
This will log progress as it moves through the files, instead of one log after all is done. It has the added advantage that, if the  user defined a custom `writeTypes` function in the config and logs something there, it will show up in the context of the file, instead of after all other output.
- Do not fail silently, when parsing threw an error for some reason. This was actually the initial motivation for improving logging. In column-info.ts there was a catch, which caught any error thrown in `addColumnInfo` and returned a default value. It did so without any output or indication of why columns would be set to nullable. This actually hid an error in `psql-ast-parser`, which [currently fails on `CROSS JOIN`s](https://github.com/oguimbal/pgsql-ast-parser/issues/49)  
To keep logging centralised in index.ts, column-info.ts throws a special error, which is caught in index.ts and triggers logging and fallback to default.

### Output before
All:
Bildschirmfoto 2022-03-22 um 10 32 34
Watch:
Bildschirmfoto 2022-03-22 um 10 32 09

### Output after
All:
Bildschirmfoto 2022-03-21 um 09 34 45
Watch:
Bildschirmfoto 2022-03-22 um 10 23 39

### CODE REVIEW

**Comment by mmkal** [comment]
@janpaepke I really like this change. I regret making this tool as forgiving of errors as it is. I was running it on a big pre-existing codebase and silently ignoring errors was a quick way of supporting gradual adoption. I like the `.recover` pattern, it's a more pragmatic way of getting something like [railway oriented programming](https://fsharpforfunandprofit.com/rop/) without going full functional.

A couple of questions/comments:

>remove need for memoization in watch

It looks like we're still memoizing, we're just using a `Map<string, string>` instead of the memoizee library. I'm not against that per se, but what was the motivation? This change scares me a bit because watch mode/memoization is near-impossible to test. And when that stuff goes wrong, it can go a bit nuts (e.g., when there's a syntax error in the code, the tool sometimes gets into an infinite loop where it keeps adding the types to the bottom of a file ad infinitum. Most of the weird code to do with watch mode is there because of painful experience. Not saying that this will have regressed anything, but since this is changing I might be a bit cautious and publish a canary version of this, and test it out on my team at work for a few weeks. Or I'd be open to merge this pretty much straight away if the watch mode changes were refactored into a separate PR.

>use paths relative to process, instead of absolute paths. This will make the output a lot more readable and keep paths 'clickable', when run inside for example vscode.

The reason the paths are absolute is for better monorepo support. The absolute paths are clickable in VSCode too. But I'll try this out, and maybe absolute paths could be added as a configuration option later if I really miss them.

**Comment by janpaepke** [comment]
### watch mode
I would have to check, but I'm not sure this change can be separated out. The motivation behind it was that now the logs (and origins of logs) are synchronised between "all files" and "watch mode". You can see that there is no message for "file was updated" as this comes from the `generateForFile` method, plus potential error handlers.

I also realized an issue with the previous memoization routine: For me It always ran twice in watch mode.
The reason being that when I saved it also triggered formatting with prettier. So It would trigger the watch, it would update the types in the file, prettier (from my vscode) would prettify them (with different settings), watch would trigger again, as it felt the content changed.
With the updated version it only runs when the content has actually changed.

I can't really see how this would go into an infinite loop unless combined with some other tool, which also auto-modifies the file.
But If it speeds up this PR I will try to separate the watch changes out.


### relative paths
The relative paths very much work in mono-repos (I use it there as well). That's the reason for making it relative to the process directory, rather than the `rootDir`.

**Comment by mmkal** [comment]
@janpaepke thanks for the explanation. I really just meant the switch from memoizee to maintaining a `Map<string, string>` manually, but rather than asking you to separate it out, I'll publish a canary package today and try it. IIRC it was when in combination with prettier/eslint in VSCode that I saw problems before. I'm sure it'll be fine though.

Relative paths - ok, I'm happy to make the switch, I don't remember it _not_ working with relative paths, and they do make the output more readable so no objections here.

**Comment by janpaepke** [comment]
Hey Misha,
oh, sorry, I misread that.
The switch to the map is because it should be much cleaner and more reliable:
We update it, when the content actually changes, not based on some arbitrary memoization-timeout.

Let me know how the field test goes.

**Comment by mmkal** [comment]
@janpaepke published as `0.11.4-feature-improve-log-output-2022-03-31-07-11-56.6`. I was to make it break horribly in vscode by introducing a syntax error, but as it turns out, that bug exists in the stable package too. So I am good with this. I've pushed latest master and an instanbul ignore statement to hopefully make the red go away. Thank you!

**Comment by janpaepke** [comment]
There's [one more line](https://codecov.io/gh/mmkal/slonik-tools/compare/c168907a333678f379cccedb182fc8282f8e17c3...db787b0371d02d7b252ad0d3e2e5719c0c3e2bee/src/packages/typegen/src/index.ts?before=packages/typegen/src/index.ts#L254) that should be ignored, as I don't really think it warrants writing a test for it: The case when the file did not change between watch handler calls.

**Comment by mmkal** [comment]
I actually can't repro that line not being covered, when I run locally it is. I'm just going to merge and move on with my life.

**Comment by mmkal** [comment]
Thank you @janpaepke!

**Pull request merged**
