### PR TITLE
improve type extraction

### PR DESCRIPTION
**Pull request by janpaepke**
- [x] refactor getColumnInfo to separate responsibilities
- [ ]  make functions idempotent
- [ ] decrease repetition
- [ ] improve field analysis

### CODE REVIEW

**Comment by janpaepke** [comment]
I decided to do this in steps, as the changes are likely going to be significant.

This is already good to review, I'll create the next pr towards this branch for individual review.

**Review by mmkal — APPROVED** [review]
Looks good! Guessing the todo items in the description are not intended for this PR?

**Comment by janpaepke** [comment]
Hey misha,

well this is really only half way there and has also changed quite a bit in my local version.
I'm still trying to figure out the best structure, but it may take a while.

We could merge this currently still only cosmetic.

**Comment by mmkal** [comment]
@janpaepke let's merge. I'd like to make some changes too, and want to reduce the chance of conflicts. Plus, cosmetic changes are still good changes! If there are small tweaks you want to make, feel free then mark ready for review. Or, if it's going to cause issues for your local somehow, let me know and I can hold off/we can figure out how to separate out this from future changes. Otherwise will just merge it at some point in the next few days.

**Comment by janpaepke** [comment]
Nah, it's good to merge.
Sorry haven't really had time for this recently, but still intend to finish it...

**Pull request merged**
